### ISSUE TITLE
Unify i18n

### ISSUE THREAD

**Issue by MangelMaxime** [rluiten/elm-date-extra#13]
Hello, shouldn't we unify the format for the i18n ?

* `I_en_us.elm` have first letter uppercase
* `I_fr_fr.elm` all words are in lowercase

**Comment by rluiten** [comment]
Yes totally, I managed to not notice that :).
I'll look into it in next day or to.
I am inclined to go with Upper case first, as all lower case could b introduced with a custom code and toLower.

**Comment by MangelMaxime** [comment]
I already have the code convert with Upper case. I will create a Pull Request in the day.
