### ISSUE TITLE
Remove Debug.log from package before publishing

### ISSUE THREAD

**Issue by cuducos** [rluiten/elm-date-extra#27]
It looks like there are two `Debug.log` that shouldn't be there (at least, not in production). Both in `Date.Extra.Internal`: [lines 18-26](https://github.com/rluiten/elm-date-extra/blob/master/src/Date/Extra/Internal.elm#L18-L26) and [30](https://github.com/rluiten/elm-date-extra/blob/master/src/Date/Extra/Internal.elm#L30).

**Comment by rluiten** [comment]
These updates should be in next release (in next few hours).

**Comment by cuducos** [comment]
Yay. Many thanks for that ; )
Count down to the ext release 🕐

**Comment by rluiten** [comment]
Hope this change doesn't cause pain for people.
Oh well we shall see.
As I can't force a Major version change as the API is the same just a constant config changed.

**Comment by cuducos** [comment]
> Hope this change doesn't cause pain for people

Please, this is not a critique but IMHO a pain for was to debug with my own `Debug.log` when `elm-date-extra` was polluting my console with a log of unrequested logs… I mean, saying it as a pain is a bit overreacting, but it was a bit annoying ; )

**Comment by rluiten** [comment]
Oops my comment about pain for others was not meant for Debug.log left overs.
I got log mixed up with Format.isoString and Format.isoMsecOffsetFormat :) sorry.

Removing Debug.log's yes totally should not do it in production or maybe provide config to allow it, but definitly not just log, it was an oversite on my part.

**Comment by cuducos** [comment]
Hahaha… got it!
