### ISSUE TITLE
Questions: I cant see to find a method to find next date.

### ISSUE THREAD

**Issue by stoivo** [rluiten/elm-date-extra#38]
I cant see to find a method to find next date. 
Does this method exist?

I can write it myself but I wondered if it exists
```elm
nextDate : Date -> Date
nextDate date
    Date.fromTime ((Date.toTime date) + 1000 * 60 * 60 * 24)

prevDate : Date -> Date
prevDate date
    Date.fromTime ((Date.toTime date) + 1000 * 60 * 60 * 24)
```

**Comment by rluiten** [comment]
Date.Extra.Duration `add : Duration -> Int -> Date -> Date`
eg `newDate = Duration.add Day 1 myDate`

or maybe this might suit in Date.Extra.Utils `dayList : Int -> Date -> List Date`

**Comment by stoivo** [comment]
You solved my case :)
