### ISSUE TITLE
Huge RAM consumption when calling Date.Extra.Utils.dayList with a negative integer.

### ISSUE THREAD

**Issue by AIon-Gbbe** [rluiten/elm-date-extra#43]
I just discovered this unusual behavior to the `dayList` function which is defined as:

`dayList : Int -> Date -> List Date`

Calling `Date.Extra.Utils.dayList -2 someDate`, creates a huge immediate bump into RAM consumption. Then the hole app gets frozen.

For positive numbers it works as expected. But I by mistake was getting a negative integer by calling:
`Date.Extra.Duration.diffDays startDate endDate`

**Comment by rluiten** [comment]
That is very funny and a good find thanks.
It is creating a massive list by subtracting 1 from your -2 until it reaches Zero :).

I hope to get to this in next day or 2.

**Comment by AIon-Gbbe** [comment]
from @tolgapaksoy in slack channel :

"i guess it’s because the recursion check is only done with `== 0`, and not `<= 0`:
https://github.com/rluiten/elm-date-extra/blob/8.5.0/src/Date/Extra/Utils.elm#L52 ."

**Comment by rluiten** [comment]
Fixed in 8.5.1.
Thanks.
