### ISSUE TITLE
Swedish localization not found

### ISSUE THREAD

**Issue by martindlarsson** [rluiten/elm-date-extra#52]
I just installed your package and wanted to use the newly added Swedish localization. Though the compiler cannot find the module Date.Extra.Config.Config_sv_se and looking in the elm_stuff folder and your package there are no such file. I can see it in your repo though.

**Comment by rluiten** [comment]
Have you got any examples of what is failing ?
I created a test case on ellie.

https://ellie-app.com/44ncdTqPFXMa1/5

**Comment by martindlarsson** [comment]
When building again I got a conflict between packages where one package only accepts versions up to 9. Probably why the file was missing. Closing until further notice.
