### ISSUE TITLE
utcIsoWeekString : Date -> String

### ISSUE THREAD

**Issue by adius** [rluiten/elm-date-extra#54]
There is already `Utils.isoWeek`, but the corresponding formatter is missing.

**Comment by rluiten** [comment]
So were you after all 3 values that isoWeek can produce ?

**Comment by rluiten** [comment]
I added all 3 fields that Utils.isoWeek can return as format fields in release 9.1.2.

**Comment by adius** [comment]
Ah, I see, thanks. I was looking for some convenience helper a la `utcIsoString`.

Btw: You should setup some type alias to make the documentation easier to read.

For example

```
format : Config -> FormatString -> Date -> FormattedDate
```

instead of 

```
format : Config -> String -> Date -> String
```

**Comment by rluiten** [comment]
That is a good idea.

Though IMO if the documentation extraction used the name of the parameters
rather as well as the types then the need for alias types has not got the
value any more.

**Comment by adius** [comment]
But many (me including) use shortcut words as parameter names as the signature already says what that parameter exactly is. e.g.

```
format : Config -> FormatString -> Date -> FormattedDate
format conf fmtStr date fmtedDate = …
```
And this would make  a shitty documentation.
(I'm exaggerating here a little, but you know what I mean…)
