### ISSUE TITLE
Conflicts with elm-date-format

### ISSUE THREAD

**Issue by eeue56** [rluiten/elm-date-extra#7]
Date.Format conflicts with elm-date-format.

All the modules in this package should be under `Date.Extra`

**Comment by rluiten** [comment]
Fair point had not considered it, Ill move it tonight after work with a new version.

**Comment by eeue56** [comment]
Thanks 💯

**Comment by rluiten** [comment]
Ok published 4.0.0 moved all modules to `Date.Extra.` name space.
